# Generated by Django 4.2.8 on 2023-12-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowResource',
            fields=[
                ('borrow_resources_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
            options={
                'db_table': 'BorrowResource',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_quantity', models.IntegerField()),
                ('resource_name', models.CharField(max_length=25)),
                ('is_available', models.BooleanField()),
            ],
            options={
                'db_table': 'Resource',
            },
        ),
    ]
