# Generated by Django 4.2.8 on 2023-12-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BorrowResource', '0001_initial'),
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowresource',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.organization'),
        ),
        migrations.AddField(
            model_name='borrowresource',
            name='resident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident'),
        ),
        migrations.AddField(
            model_name='borrowresource',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BorrowResource.resource'),
        ),
    ]
