# Generated by Django 4.2.8 on 2023-12-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('I', 'Certificate of Indigency'), ('B', 'Barangay Clearance'), ('R', 'Certificate of Residency'), ('P', 'Barangay Business Permit'), ('F', 'Certificate of First-Time Job Seeker'), ('D', 'PWD ID')], max_length=1)),
                ('fee', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfApproval', models.DateField()),
                ('requestStatus', models.CharField(max_length=10)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RequestDocument.document')),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident')),
            ],
            options={
                'db_table': 'Document_Request',
            },
        ),
    ]
