# Generated by Django 4.2.8 on 2023-12-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0002_initial'),
        ('RequestDocument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='resident_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident'),
        ),
    ]
