# Generated by Django 4.2.8 on 2023-12-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookAppointment', '0001_initial'),
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='residents',
            field=models.ManyToManyField(through='BookAppointment.Appointment', to='CreateAccount.resident'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='healthCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookAppointment.healthcenter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident'),
        ),
    ]
